### ISSUE TITLE
System layout

### ISSUE THREAD

**Issue by JanSmrcka** [eli-eric/ELI-panda#121]
- [x]  same bradcrump like in catalogue
- [x] system name to system detail
- [x] change layout of system detail -> general item component
- [x] connect to real endpoints
- [x] search results to grid -> no query url paging
- [x] rootsystems -> breadcrump -> button for add subsystem
- [x] repair relation table
- [x] clean up system module
- [x] POST system/{uid}/item, obsolete to boolean
- [x] implement autocomplete box - locations, users

## Codebooks
- [x] GET /codebook/{codebook_code}?parentUID(optional)  [ { uid, name }]
List of codebooks codes available:

- SYSTEM_TYPE
- SYSTEM_IMPORTANCE
- SYSTEM_CRITICALITY_CLASS
- LOCATION
- ZONE
- SUB_ZONE (with parentUID=ZONE.uid)
- ITEM_USAGE
- ITEM_CONDITION_STATUS
- USER

## Systems

- [x] GET /system/subsystems/{parentUID}  [ {uid, name} ]

- [x] GET /system/{uid} { SystemResponse }

- [x] GET /system/{uid}/image   base64string

- [x] POST /system        body: SystemForm  response:  { message: string } // general response type ApiResponse = { message: string }

- [x] PUT /system/{uid}      body: SystemForm  response: ApiResponse { message: string }

- [x] DELETE /system/{uid}  response: ApiResponse { message: string }

- [x] GET /systems?pagination={page, pageSize}&search=string  {totalCount, System[]}

payloads:
```
export type SystemResponse = {
  uid: string
  name: string
  parentPath: [ {name, uid } ]
  description?: string
  location?: {uid:string, name: string}
  zone?: {uid:string, name: string}
  systemType?: {uid:string, name: string}
  systemCode?: string
  systemAlias?: string
  owner?: {uid:string, name: string} 
  importance?: {uid:string, name: string}
  itemUID?: string 
}

export type SystemForm = {
  name: string
  parentUID?: string // parent system uid
  description?: string
  systemTypeUID?: string  // system types codebook - SYSTEM_TYPE
  systemCode?: string
  systemAlias?: string
  locationUID?: string // locations codebook - LOCATION
  itemUID?: string // connected item -> then connected catalogueUID -> catalogue item
  ownerUID?: string // codebook of users{uid, name}  - USER
  importanceUID?: string  // codebook of importance - SYSTEM_IMPORTANCE
  zoneUID?: string // codebook of zones - ZONE   
}
```

## Item

- [x] POST /system/{uid}/item  { SystemItemForm }  response: ApiResponse { message: string }
payload:
```
SystemItemForm
 {
  "catalogueItemUID": "a56014ab-f3e2-4884-a600-38be506bdf5b",
  "itemUsageUID": "0119a645-5155-46a4-95a4-4ad576d4fff2",  // codebook ITEM_USAGE
  "eun": "sad",
  "description": "asdfsdfdsfsdfsd",
  "serialNumber": "asd",
  "batchNumber": "asdasd",
  "obsolete": "false",
  "estimatedLifeTimeYears": "111",
  "conditionStatusUID": "uid........" // codebook ITEM_CONDITION_STATUS
} 
```

## Relationships
- [x] GET /system/{uid}/relationships [ { direction: string, relationTypeCode: string, foreignSystemName: string, systemName: string, relationUid: string } ] // direction could be "from" or "to", relationUid: string - don't show to user - only for delete

- [x] GET /systems/for-relationship?systemFromUid=57392070-40c6-4be6-97e2-ee1e406dd6cf&relationTypeCode=IS_SPARE_FOR&search=asda&pagination={"page":1,"pageSize":10} { System[], totalCount }

- [x] POST /system/relationship { systemFromUID:string, systemToUID: string, relationTypeCode: string }

- [x] DELETE /system/relationship/{uid}   {message: string}

relationships grid:
![relationships_systems drawio](https://user-images.githubusercontent.com/88783077/222095725-73a8a4cd-58dd-4b80-8124-b5d07c336745.png)

**Comment by JanSmrcka** [comment]
Added codebooks to catalogue edit form.

**Comment by JanSmrcka** [comment]
implemented EPS:
GET /system/subsystems/{parentUID} [ {uid, name} ]
GET /system/{uid} { SystemResponse }
GET /system/{uid}/image base64string

**Comment by svachaj** [comment]
New type of codebook endpoint - autocomplete codebook - in case of a lot of data:

GET /codebook/autocomplete/{codebook_code}?searchText=abc&limit=10

- limit is optional when default from server is limit=10 (max is 100)
- searchText is optional


Implemented codebooks(codebook_code):
- LOCATION  (if no searchText then no data returned)
- USERS  (if no searchText then fist 10 items returned)

**Comment by svachaj** [comment]
codebooks and autocomplete codebooks are ready and deployed in production (https://api.panda.eli-beams.eu/)

**Comment by JanSmrcka** [comment]
added fetching codebooks in system add/edit modal, system edit modal layout.

**Comment by JanSmrcka** [comment]
added system edit form POST, PUT and GET system detail.

**Comment by JanSmrcka** [comment]
Finished search, systemItem.
