### ISSUE TITLE
Generate systemCode automaticaly

### ISSUE THREAD

**Issue by svachaj** [eli-eric/ELI-panda#148]
The systemCode in System edit form should be automacilay generated depend on the fields: systemType, zone, location
EP : GET /system/systemCode queryParams: systemTypeUID, zoneUID, locationUID, parentUID return 200 and simple string as the generated systemCode
- real EP not ready yet

**Comment by JanSmrcka** [comment]
@svachaj and what about to remove systemCode from form and backend on submit form will do it behind? I think its strange to have endpoint for this. Or we have to show it to user? User can see system code on detail screen.
