### ISSUE TITLE
Create real API endpoints

### ISSUE THREAD

**Issue by svachaj** [eli-eric/ELI-panda#28]
## Codebooks
- [x] GET /codebook/{codebook_code}?parentUID(optional)  [ { uid, name }]
List of codebooks codes available:

- SYSTEM_TYPE
- SYSTEM_IMPORTANCE
- SYSTEM_CRITICALITY_CLASS
- LOCATION
- ZONE
- SUB_ZONE (with parentUID=ZONE.uid)
- ITEM_USAGE
- ITEM_CONDITION_STATUS
- USER

## Systems

- [x] GET /systems/subsystems/{parentUID}  [ {uid, name} ]

- [x] GET /system/{uid} { SystemResponse }

- [x] GET /system/{uid}/image   base64string

- [x] POST /system        body: SystemForm  response:  { message: string } // general response type ApiResponse = { message: string }

- [x] PUT /system/{uid}      body: SystemForm  response: ApiResponse { message: string }

- [x] DELETE /system/{uid}  response: ApiResponse { message: string }

- [x] GET /systems?pagination={page, pageSize}&search=string  {totalCount, System[]}

payloads:
```
export type SystemResponse = {
  uid: string
  name: string
  parentPath: [ {name, uid } ]
  description?: string
  location?: {uid:string, name: string}
  zone?: {uid:string, name: string}
  systemType?: {uid:string, name: string}
  systemCode?: string
  systemAlias?: string
  owner?: {uid:string, name: string} 
  importance?: {uid:string, name: string}
  itemUID?: string 
}

export type SystemForm = {
  name: string
  parentUID?: string // parent system uid
  description?: string
  systemTypeUID?: string  // system types codebook - SYSTEM_TYPE
  systemCode?: string
  systemAlias?: string
  locationUID?: string // locations codebook - LOCATION
  itemUID?: string // connected item -> then connected catalogueUID -> catalogue item
  ownerUID?: string // codebook of users{uid, name}  - USER
  importanceUID?: string  // codebook of importance - SYSTEM_IMPORTANCE
  zoneUID?: string // codebook of zones - ZONE   
}
```

## Item

- [x] POST /system/{uid}/item  { SystemItemForm }  response: ApiResponse { message: string }
payload:
```
SystemItemForm
 {
  "catalogueItemUID": "a56014ab-f3e2-4884-a600-38be506bdf5b",
  "itemUsageUID": "0119a645-5155-46a4-95a4-4ad576d4fff2",  // codebook ITEM_USAGE
  "eun": "sad",
  "description": "asdfsdfdsfsdfsd",
  "serialNumber": "asd",
  "batchNumber": "asdasd",
  "obsolete": "false",
  "estimatedLifeTimeYears": "111",
  "conditionStatusUID": "uid........" // codebook ITEM_CONDITION_STATUS
} 
```

## Relationships
- [ ] GET /system/{uid}/relationships [ { direction: string, relationTypeCode: string, foreignSystemName: string, systemName: string, relationUid: string } ] // direction could be "from" or "to", relationUid: string - don't show to user - only for delete

- [ ] GET /systems/for-relationship?systemFromUid=57392070-40c6-4be6-97e2-ee1e406dd6cf&relationTypeCode=IS_SPARE_FOR&search=asda&pagination={"page":1,"pageSize":10} { System[], totalCount }

- [ ] POST /system/relationship { systemFromUID:string, systemToUID: string, relationTypeCode: string }

- [ ] DELETE /system/relationship/{uid}   {message: string}

relationships grid:
![relationships_systems drawio](https://user-images.githubusercontent.com/88783077/222095725-73a8a4cd-58dd-4b80-8124-b5d07c336745.png)

**Comment by noobadmin** [comment]
- `/system/id` get, put, post, delete
  - post adds a new "child" to an existing system
- `/systems`
  - accepts uri params `id` & `fields`
  - it can but doesn't have to return "root children" if no `id`s are specified.
-  `/systems/search`
  - accepts uri params `query` & `fields` 
  
This is more of an idea, feel free to rename things etc.

`/systems/` should be paginated, but it's not that important right now, consider using an arbitrary limit (50?) for now
